repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: run-pytest
        name: Run pytest
        entry: pytest --rootdir . --maxfail=1 --disable-warnings
        language: system
        pass_filenames: false

